# Generated by Django 2.1.3 on 2018-12-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(choices=[('NJ', 'New Jersey'), ('NY', 'New York'), ('PA', 'Pennsylvania'), ('CT', 'Connecticut')], default='NJ', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', max_length=5),
        ),
    ]
