# Generated by Django 2.1.3 on 2019-02-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactList', '0003_auto_20190213_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitutde',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
