# Generated by Django 2.1.3 on 2019-02-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactList', '0005_auto_20190213_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='longitutde',
            new_name='longitude',
        ),
    ]
